### ISSUE TITLE
Winking face

### ISSUE THREAD

**Issue by vivkay** [vivkay/blink#1]
Hi @thomasjbradley! Am playing with transitions and drawing in CSS. I got to make the eyes squiggle when you hover, and the face blushes when you hover also. 

I'm struggling with conceptualizing how I would use css animations to make the face appear to wink or blink. I thought of:
1. Drawing two orange circles ("eyelids") the same size as the white eye circle, and placing them in an independent div with position relative. Then adding an opacity transition to them... but I struggled to find the right coordinates to cover the eye (math!!)
2. Is it possible to target multiple elements (i.e. eye1, eye2, iris1, iris2) simultaneously and use an opacity transition to make them disappear and reappear?

And finally, is this rotating circle (spinning eye wheels of craziness!) possible with css? This person uses .js...
http://lea.verou.me/2012/02/moving-an-element-along-a-circle/

THANKS!

V

**Comment by vivkay** [comment]
http://vivkay.github.io/blink/

**Comment by thomasjbradley** [comment]
_Question 1:_

Your idea of having an orange circle that covers over the eyes makes sense to me. I probably would put them above they eyes, then animate them down, kinda like this illustration:

![face-with-eyelid](https://cloud.githubusercontent.com/assets/105192/5724355/f6d3eace-9b18-11e4-8d0d-73d71bcd0643.png)
(I would make the eyelid match the face though—it's just red to show you where I'd put it.)

---

_Question 2:_

Targeting multiple elements: you could use a comma, like:

``` css
.eye1, .eye2, .iris1, .iris2 {

}
```

---

_Final comment:_

Yep, spinning circles was exactly what I was going to show you in class next week!
It's done with the `animation` CSS property and `transform: rotate()`.

**Comment by vivkay** [comment]
Thanks! will try this out!
